AllCops:
  DisabledByDefault: true
  SuggestExtensions: false

require:
  - rubocop-packs

inherit_gem:
  rubocop-packs:
    - config/default.yml

Packs/DocumentedPublicApis:
  Enabled: true

Packs/RootNamespaceIsPackName:
  Enabled: true
  Exclude:
  - packs/rails_shims/**/*

Style/StringLiterals:
  EnforcedStyle: double_quotes