enforce_architecture: strict
enforce_dependencies: strict
enforce_privacy: strict

dependencies:
- packs/books
- packs/contact
- packs/nav_bar
- packs/posts
- packs/rails_shims
- packs/root
- packs/speaking

layer: application_harness