enforce_architecture: strict
enforce_dependencies: strict
enforce_privacy: strict

dependencies:
- packs_userfacing/agile_landscape
- packs_userfacing/books
- packs_userfacing/contact
- packs_userfacing/posts
- packs_userfacing/root
- packs_userfacing/services
- packs_userfacing/speaking
- packs_userfacing/tags
- packs_utility/rails_shims
- packs_utility/routable
- packs_utility/taggable

layer: application_harness
