enforce_architecture: strict
enforce_dependencies: strict
enforce_privacy: strict

dependencies:
- packs/agile_landscape
- packs/books
- packs/contact
- packs/posts
- packs/rails_shims
- packs/root
- packs/services
- packs/speaking
- packs/taggable
- packs/tags

layer: application_harness