enforce_architecture: strict
enforce_dependencies: strict
enforce_privacy: strict

dependencies:
- packs_userfacing/contact
- packs_utility/backlinks
- packs_utility/rails_shims
- packs_utility/routable
- packs_utility/taggable

layer: userfacing
